---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-redis
  namespace: vitorcruz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverless-redis
  template:
    metadata:
      labels:
        app: serverless-redis
    spec:
      containers:
        - name: serverless-redis
          image: vitorugoc/serverless:03
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
          volumeMounts:
            - name: pyfile
              mountPath: "/opt/usermodule.py"
              subPath: pyfile
            - name: usermodule
              mountPath: "/opt/usermodule.zip"
              subPath: usermodule.zip
          env:
            - name: REDIS_HOST
              value: "192.168.121.187"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_INPUT_KEY
              value: "metrics"
            - name: REDIS_MONITORING_PERIOD
              value: "5"
            - name: ZIP_FILE_PATH
              value: "/opt/usermodule.zip"
            - name: ENTRY_FUNCTION
              value: "handler"
            - name: REDIS_OUTPUT_KEY
              valueFrom:
                configMapKeyRef:
                  name: outputkey
                  key: REDIS_OUTPUT_KEY
      volumes:
        - name: pyfile
          configMap:
            name: pyfile
        - name: usermodule
          configMap:
            name: usermodule
